import { NextResponse } from "next/server";

export async function POST(req: Request) {
    try {
        const { focal, partnersInfo } = await req.json();

        if (!focal || !partnersInfo) {
            return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
        }

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: "GEMINI_API_KEY is not configured on the server." }, { status: 500 });
        }

        const prompt = `You are an expert RNA biologist and computational biologist.
I am analyzing RNA-RNA interaction data (chimeras) generated by a method similar to RIL-seq, TRIC-seq, or CLASH.
I am looking at a focal RNA named "${focal}".
Here is a list of its top interacting partners along with their feature types, interaction counts (reads), and odds ratios/FDR values if available:

${partnersInfo}

Based ONLY on the identities and feature types of these interacting RNAs, formulate a strong, specific biological hypothesis regarding the exact function, regulatory mechanism, and cellular role of "${focal}".
Do not just give a generic answer like "it likely functions as an sRNA that modulates mRNA". Instead, carefully look at the names of the specific target genes provided in the list (if they are known mRNAs/CDS like ompA, luxS, etc.). Deduce their known biological functions and pathways.
Then, postulate precisely what physiological process "${focal}" is regulating based on the shared pathways of those specific targets.
For example, if it frequently interacts with mRNAs of specific pathways (e.g., ABC transporters, metabolism, virulence), state exactly what those pathways are based on the gene names.

Keep your response extremely concise, highly specific to the provided gene names, scientific, and no longer than two short paragraphs. Do not mention that you are an AI or give generic warnings.`;

        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: prompt
                    }]
                }],
                generationConfig: {
                    maxOutputTokens: 800,
                    temperature: 0.7,
                }
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error("Gemini API error:", errorText);
            return NextResponse.json({ error: `Gemini API failed with status ${response.status}` }, { status: response.status });
        }

        const data = await response.json();
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!generatedText) {
            return NextResponse.json({ error: "No text returned from Gemini API." }, { status: 500 });
        }

        return NextResponse.json({ hypothesis: generatedText });
    } catch (error: any) {
        console.error("Error in hypothesis route:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}
